# Default values for contract-repayments-calculator
replicaCount: 1

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

image:
  repository: contract-repayments-calculator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

springBoot:
  profile: prod
  javaOpts: -Xmx512m -Xms256m

h2Database:
  enabled: true
  persistence:
    enabled: true
    storageClass: standard
    size: 1Gi
  config:
    dbName: repaymentdb
    username: sa
    password: password
