openapi: 3.0.3
info:
  title: Contract Repayments Calculator API
  description: API for calculating device contract repayments with various payment terms
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: Contract Repayments Calculator
    description: Operations for contract repayment calculations and user management

paths:
  /api/v1/contracts:
    get:
      tags:
        - Contract Repayments Calculator
      summary: Show calculator web interface
      description: Returns the calculator web interface
      operationId: showCalculator
      responses:
        '200':
          description: Calculator page successfully returned
          content:
            text/html:
              schema:
                type: string

  /api/v1/contracts/calculate:
    post:
      tags:
        - Contract Repayments Calculator
      summary: Calculate repayments from web form
      description: Process device details and calculate repayments
      operationId: calculateResults
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DeviceDetails'
      responses:
        '200':
          description: Calculation successful
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: string

  /api/v1/contracts/repayments:
    get:
      tags:
        - Contract Repayments Calculator
      summary: Calculate device repayment options
      description: Calculates monthly repayments for a device over 12, 24, and 36 month periods with 6.5% interest
      operationId: calculateRepayments
      parameters:
        - name: amount
          in: query
          required: true
          description: Device amount to finance
          schema:
            type: number
            format: double
            minimum: 0.01
            example: 1000.00
      responses:
        '200':
          description: Successful calculation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentResult'
        '400':
          description: Invalid amount provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/contracts/users:
    post:
      tags:
        - Contract Repayments Calculator
      summary: Register new user
      description: Register a new user in the system
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDetails'
      responses:
        '200':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid user details provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    DeviceDetails:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          format: double
          example: 1000.00
          description: Device amount to finance

    CustomerDetails:
      type: object
      required:
        - email
        - name
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        name:
          type: string
          example: John Doe

    PaymentResult:
      type: object
      properties:
        paymentPeriods:
          type: integer
          enum: [12, 24, 36]
          example: 12
          description: Number of months for repayment
        monthlyPayments:
          type: number
          format: double
          example: 87.50
          description: Monthly payment amount

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Error message
        timestamp:
          type: string
          format: date-time

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []